<!DOCTYPE quizgame [
<!ELEMENT quizgame (gamesettings?, rooms, doors, quizquestions)>
<!ELEMENT rooms (room+)>
<!ELEMENT room (transform)>
<!ELEMENT transform (position, rotation, scale)>
<!ELEMENT doors (door+)>
<!ELEMENT quizquestions (quizquestion+)>
<!ELEMENT quizquestion (question, option+)>
<!ELEMENT gamesettings ANY>
<!ELEMENT position EMPTY>
<!ELEMENT rotation EMPTY>
<!ELEMENT scale EMPTY>
<!ELEMENT door EMPTY>
<!ATTLIST room prefab_name CDATA #REQUIRED next_to_room CDATA #REQUIRED hide_door_cover_at_wall CDATA #REQUIRED>
<!ATTLIST position x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED>
<!ATTLIST rotation x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED>
<!ATTLIST scale x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED>
<!ATTLIST door prefab_name CDATA #REQUIRED>
<!ATTLIST door limit_points CDATA #REQUIRED>
<!ATTLIST quizquestion idx CDATA #REQUIRED>
<!ATTLIST quizquestion points CDATA #REQUIRED>
<!ATTLIST option idx CDATA #REQUIRED>
<!ATTLIST option isTrue (true | false) #REQUIRED>
<!ELEMENT question (#PCDATA)>
<!ELEMENT option (#PCDATA)>
]>

<!-- IMPORTANT NOTE: Decimal separator for float values must be a comma "," ! -->

<quizgame>
    <gamesettings>
    </gamesettings>

    <rooms>
                <room prefab_name="RoomsAll" next_to_room="Anteroom" hide_door_cover_at_wall="WallS">
                    <transform>
                    <position x="29,3" y="3,15" z="-44,01"/>
                    <rotation x="0" y="-90" z="0"/>
                    <scale x="1" y="1" z="1"/>
                    </transform>
                </room>
    </rooms>

    <doors>
                <door prefab_name="Room1 Exit" limit_points="50"/>
                <door prefab_name="Room_2_Intermediary_Gate_1" limit_points="100"/>
                <door prefab_name="Room3_Entrance" limit_points="150"/>
                <door prefab_name="Tower_Door" limit_points="200"/>
                <door prefab_name="Barrel_Secret_Entrance" limit_points="200"/>
    </doors>

    <quizquestions>
                <quizquestion idx="0" points="10">
                    <question>Как се нарича подреждането на събитията, според последователността, в която са се случили:</question>
                    <option idx="0" isTrue="false">История</option>
                    <option idx="1" isTrue="true">Хронология</option>
                    <option idx="2" isTrue="false">Геология</option>
                </quizquestion>
                <quizquestion idx="1" points="15">
                    <question>Кое тракийско племе създава голяма и трайна държава:</question>
                    <option idx="0" isTrue="true">Одриси</option>
                    <option idx="1" isTrue="false">Беси</option>
                    <option idx="2" isTrue="false">Мизи</option>
                </quizquestion>
                <quizquestion idx="2" points="15">
                    <question>Кой български цар победил епирския владетел Теодор Комнин в битката при Клокотница на 9 март 1230 г. “:</question>
                    <option idx="0" isTrue="false">Калоян</option>
                    <option idx="1" isTrue="false">Симеон</option>
                    <option idx="2" isTrue="true">Иван Асен II</option>
                </quizquestion>
                <quizquestion idx="3" points="10">
                    <question>Кой български хан победил арабите край Константинопол през 718 г., като по този начин спасил Европа от тяхното нашествие:</question>
                    <option idx="0" isTrue="false">Аспарух</option>
                    <option idx="1" isTrue="true">Тервел</option>
                    <option idx="2" isTrue="false">Омуртаг</option>
                </quizquestion>
                <quizquestion idx="4" points="15">
                    <question>Апокрифите са:</question>
                    <option idx="0" isTrue="false">Произведения, описващи живота на светци</option>
                    <option idx="1" isTrue="true">Анонимни средновековни ръкописи</option>
                    <option idx="2" isTrue="false">Записи на устната традиция за живота на християнски мъченици</option>
                </quizquestion>
                <quizquestion idx="5" points="10">
                    <question>Славянската писменост, създадена от Кирил и Методий, е известна като:</question>
                    <option idx="0" isTrue="false">Кирилица</option>
                    <option idx="1" isTrue="true">Глаголица</option>
                    <option idx="2" isTrue="false">Димотическо писмо</option>
                </quizquestion>
                <quizquestion idx="6" points="10">
                    <question>Според Търновската конституция България е:</question>
                    <option idx="0" isTrue="false">Абсолютна монархия</option>
                    <option idx="1" isTrue="false">Парламентарна република</option>
                    <option idx="2" isTrue="true">Наследствена монархия с народно събрание</option>
                </quizquestion>
                <quizquestion idx="7" points="20">
                    <question>Кой е първият генерал-губернатор на Източна Румелия”:</question>
                    <option idx="0" isTrue="false">Марко Балабанов</option>
                    <option idx="1" isTrue="false">Захари Стоянов</option>
                    <option idx="2" isTrue="true">Алеко Богориди</option>
                </quizquestion>
                <quizquestion idx="8" points="20">
                    <question>Кой известен чужденец е изпратил от Пазарджик кореспонденция за жертвите в Батак през 1876 г.:</question>
                    <option idx="0" isTrue="false">Юджийн Скайлър</option>
                    <option idx="1" isTrue="true">Джанюариъс Макгахан</option>
                    <option idx="2" isTrue="false">Х. Елиът</option>
                </quizquestion>
                <quizquestion idx="9" points="10">
                    <question>Датата 3 април 1860 г. се свързва с:</question>
                    <option idx="0" isTrue="false">Избухването на Априлското въстание</option>
                    <option idx="1" isTrue="true">Провеждането на Великденската акция</option>
                    <option idx="2" isTrue="false">Учредяването на Априловската гимназия</option>
                </quizquestion>
                <quizquestion idx="10" points="0">
                    <question>Коя от Великите сили се обявява в защита на Съединението</question>
                    <option idx="0" isTrue="false">Франция</option>
                    <option idx="1" isTrue="false">Русия</option>
                    <option idx="2" isTrue="true">Англия</option>
                </quizquestion>
                <quizquestion idx="11" points="10">
                    <question>Коя е южната граница на създадената през 681 г. Дунавска България</question>
                    <option idx="0" isTrue="false">Карпатите</option>
                    <option idx="1" isTrue="true">Стара планина</option>
                    <option idx="2" isTrue="false">Черно море</option>
                </quizquestion>
                <quizquestion idx="12" points="10">
                    <question>Хан Омуртаг въвежда комитатите, за да:</question>
                    <option idx="0" isTrue="false">Стимулира развитието на търговията</option>
                    <option idx="1" isTrue="false">Разшири границите на ханството</option>
                    <option idx="2" isTrue="true">Централизира държавата</option>
                </quizquestion>
                <quizquestion idx="13" points="15">
                    <question>Хрисовулът е:</question>
                    <option idx="0" isTrue="false">Златна монета</option>
                    <option idx="1" isTrue="false">Съд за вино</option>
                    <option idx="2" isTrue="true">Златопечатна грамота</option>
                </quizquestion>
                <quizquestion idx="14" points="15">
                    <question>Вторият български монарх след Освобождението е:</question>
                    <option idx="0" isTrue="false">Александър Батенберг</option>
                    <option idx="1" isTrue="true">Фердинад І</option>
                    <option idx="2" isTrue="false">Симеон ІІ</option>
                </quizquestion>
                <quizquestion idx="15" points="10">
                    <question>Освободителното въстание на Асеневци избухва през:</question>
                    <option idx="0" isTrue="false">1187 г.</option>
                    <option idx="1" isTrue="true">1185 г.</option>
                    <option idx="2" isTrue="false">1196 г.</option>
                </quizquestion>
                <quizquestion idx="16" points="15">
                    <question>През 1846 г. Найден Геров организира в Копривщица:</question>
                    <option idx="0" isTrue="true">Първото класно училище</option>
                    <option idx="1" isTrue="false">Първата гимназия</option>
                    <option idx="2" isTrue="false">Първото читалище</option>
                </quizquestion>
                <quizquestion idx="17" points="20">
                    <question>Св. Методий е назначен за архиепископ в:</question>
                    <option idx="0" isTrue="true">Великоморавия</option>
                    <option idx="1" isTrue="false">Панония</option>
                    <option idx="2" isTrue="false">Германия</option>
                </quizquestion>
                <quizquestion idx="18" points="15">
                    <question>Първият български екзарх е:</question>
                    <option idx="0" isTrue="false">Антим І</option>
                    <option idx="1" isTrue="true">Иларион Ловчански</option>
                    <option idx="2" isTrue="false">Йосиф І</option>
                </quizquestion>
                <quizquestion idx="19" points="10">
                    <question>Априлското въстание е обявено на 20 април 1876 г. в:</question>
                    <option idx="0" isTrue="false">Панагюрище</option>
                    <option idx="1" isTrue="true">Копривщица</option>
                    <option idx="2" isTrue="false">Стрелча</option>
                </quizquestion>
    </quizquestions>

</quizgame>